### ISSUE TITLE
free shipping coupon not working with this extension

### ISSUE THREAD

**Issue by asharjanjua** [magepal/magento2-custom-shipping-rate#8]
I installed this extension. After that i setup cart rules for free
shipping. I created a copoun in Marketing -> cart Price Rule . On checkout
page when i select custom shipping rated of this extension and apply a
coupon then nothing happens. coupon donot reduce shipping price.

**Comment by srenon** [comment]
1. 9/10 this is not an issue with this extension

2. If it not worth your time to spend 1 minute to fill out the issue template completely so that I can better understand what version of Magento you are having an issue and test using that version to try to replicate using that version so that I can solve this quickly. Then why should it worth my time (plus this is the second time you are doing it https://github.com/magepal/magento2-reindex/issues/3#issuecomment-419058131)

**Comment by asharjanjua** [comment]
I test is again and again but this is issue.
If you just set cart price rule and select custom shipping price of your extension . When we apply coupon or meet conditions then shipping cost will not decrease according to our rules.

**Comment by oviliz** [comment]
@asharjanjua , you are using an old version of both Magento and this extension. Also, you're not listening...
